version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sistema_doacao
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'      
      MYSQL_DATABASE: 'sistema_doacao' 
    ports:
      - "3306:3306"                    
    volumes:
      - mysql_data:/var/lib/mysql      

volumes:
  mysql_data: